"""screening tables

Revision ID: 15dde5b16638
Revises: f6bf1891cf53
Create Date: 2026-09-27 20:36:29.605778
"""
from alembic import op
import sqlalchemy as sa


revision = '15dde5b16638'
down_revision = 'f6bf1891cf53'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('screening_policies',
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('change_note', sa.String(), nullable=True),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_screening_policies')),
    sa.UniqueConstraint('tenant_id', 'version', name=op.f('uq_screening_policies_tenant_id'))
    )
    op.create_table('screening_runs',
    sa.Column('universe', sa.String(), nullable=False),
    sa.Column('policy_version', sa.Integer(), nullable=False),
    sa.Column('mandate_version', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('instruments', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_screening_runs'))
    )
    op.create_table('screening_results',
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('instrument_id', sa.String(), nullable=False),
    sa.Column('score', sa.Double(), nullable=False),
    sa.Column('applicable', sa.Integer(), nullable=False),
    sa.Column('qualified', sa.Boolean(), nullable=False),
    sa.Column('verdict', sa.String(), nullable=False),
    sa.Column('blocked_reasons', sa.JSON(), nullable=False),
    sa.Column('criteria', sa.JSON(), nullable=False),
    sa.Column('as_of', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], name=op.f('fk_screening_results_instrument_id_instruments')),
    sa.ForeignKeyConstraint(['run_id'], ['screening_runs.id'], name=op.f('fk_screening_results_run_id_screening_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_screening_results')),
    sa.UniqueConstraint('run_id', 'instrument_id', name=op.f('uq_screening_results_run_id'))
    )
    op.create_index('ix_screening_instr', 'screening_results', ['instrument_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_screening_results_run_id'), 'screening_results', ['run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_screening_results_run_id'), table_name='screening_results')
    op.drop_index('ix_screening_instr', table_name='screening_results')
    op.drop_table('screening_results')
    op.drop_table('screening_runs')
    op.drop_table('screening_policies')
    # ### end Alembic commands ###
