"""execution: broker orders, events, kill switch

Revision ID: 29ff37e80b18
Revises: 99661467dcbc
Create Date: 2026-09-27 22:12:23.119408
"""
from alembic import op
import sqlalchemy as sa


revision = '29ff37e80b18'
down_revision = '99661467dcbc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('execution_events',
    sa.Column('order_id', sa.String(), nullable=False),
    sa.Column('stage', sa.String(), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_execution_events'))
    )
    op.create_index(op.f('ix_execution_events_order_id'), 'execution_events', ['order_id'], unique=False)
    op.create_table('kill_switch',
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('actor', sa.String(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_kill_switch'))
    )
    op.create_table('broker_orders',
    sa.Column('order_ticket_id', sa.String(), nullable=False),
    sa.Column('instrument_id', sa.String(), nullable=False),
    sa.Column('broker', sa.String(), nullable=False),
    sa.Column('broker_order_id', sa.String(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=32), nullable=False),
    sa.Column('side', sa.String(), nullable=False),
    sa.Column('qty', sa.Double(), nullable=False),
    sa.Column('order_type', sa.String(), nullable=False),
    sa.Column('limit_price', sa.Double(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('filled_qty', sa.Double(), nullable=False),
    sa.Column('avg_fill_price', sa.Double(), nullable=True),
    sa.Column('commission', sa.Double(), nullable=True),
    sa.Column('reject_reason', sa.String(), nullable=True),
    sa.Column('submit_latency_ms', sa.Integer(), nullable=True),
    sa.Column('risk_policy_version', sa.String(length=64), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], name=op.f('fk_broker_orders_instrument_id_instruments')),
    sa.ForeignKeyConstraint(['order_ticket_id'], ['order_tickets.id'], name=op.f('fk_broker_orders_order_ticket_id_order_tickets')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_broker_orders'))
    )
    op.create_index(op.f('ix_broker_orders_idempotency_key'), 'broker_orders', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_broker_orders_order_ticket_id'), 'broker_orders', ['order_ticket_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_broker_orders_order_ticket_id'), table_name='broker_orders')
    op.drop_index(op.f('ix_broker_orders_idempotency_key'), table_name='broker_orders')
    op.drop_table('broker_orders')
    op.drop_table('kill_switch')
    op.drop_index(op.f('ix_execution_events_order_id'), table_name='execution_events')
    op.drop_table('execution_events')
    # ### end Alembic commands ###
