"""secret store

Revision ID: 2adcbe41b214
Revises: cb4a37b1fcd3
Create Date: 2026-09-28 01:25:15.358434
"""
from alembic import op
import sqlalchemy as sa


revision = '2adcbe41b214'
down_revision = 'cb4a37b1fcd3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('secret_store',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_secret_store')),
    sa.UniqueConstraint('key', name=op.f('uq_secret_store_key'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('secret_store')
    # ### end Alembic commands ###
