"""regime runs

Revision ID: 69223d6b2b5b
Revises: acf3fda77352
Create Date: 2026-09-27 21:14:49.344324
"""
from alembic import op
import sqlalchemy as sa


revision = '69223d6b2b5b'
down_revision = 'acf3fda77352'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('regime_runs',
    sa.Column('as_of', sa.DateTime(timezone=True), nullable=False),
    sa.Column('rules_version', sa.String(), nullable=False),
    sa.Column('econ_regime', sa.String(), nullable=False),
    sa.Column('market_regime', sa.String(), nullable=False),
    sa.Column('fear_greed', sa.Integer(), nullable=True),
    sa.Column('overlay', sa.String(), nullable=True),
    sa.Column('vix', sa.Double(), nullable=True),
    sa.Column('vix_band', sa.String(), nullable=True),
    sa.Column('features', sa.JSON(), nullable=False),
    sa.Column('rule_hits', sa.JSON(), nullable=False),
    sa.Column('stale_inputs', sa.JSON(), nullable=False),
    sa.Column('sector_preferences', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_regime_runs'))
    )
    op.create_index('ix_regime_asof', 'regime_runs', ['as_of'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_regime_asof', table_name='regime_runs')
    op.drop_table('regime_runs')
    # ### end Alembic commands ###
