"""pyramid trades + risk checks

Revision ID: 8bd3a06e91c9
Revises: 69223d6b2b5b
Create Date: 2026-09-27 21:43:21.129838
"""
from alembic import op
import sqlalchemy as sa


revision = '8bd3a06e91c9'
down_revision = '69223d6b2b5b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('risk_checks',
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('side', sa.String(), nullable=False),
    sa.Column('notional', sa.Double(), nullable=False),
    sa.Column('allowed', sa.Boolean(), nullable=False),
    sa.Column('breaches', sa.JSON(), nullable=False),
    sa.Column('limits_snapshot', sa.JSON(), nullable=False),
    sa.Column('engine_version', sa.String(), nullable=False),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('checked_by', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_risk_checks'))
    )
    op.create_table('pyramid_trades',
    sa.Column('instrument_id', sa.String(), nullable=False),
    sa.Column('portfolio_id', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('entry', sa.Double(), nullable=False),
    sa.Column('atr_initial', sa.Double(), nullable=False),
    sa.Column('shares', sa.Integer(), nullable=False),
    sa.Column('stop', sa.Double(), nullable=False),
    sa.Column('target1', sa.Double(), nullable=False),
    sa.Column('t2_policy', sa.String(), nullable=False),
    sa.Column('additions', sa.Integer(), nullable=False),
    sa.Column('engine_version', sa.String(), nullable=False),
    sa.Column('events', sa.JSON(), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], name=op.f('fk_pyramid_trades_instrument_id_instruments')),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], name=op.f('fk_pyramid_trades_portfolio_id_portfolios')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pyramid_trades'))
    )
    op.create_index('ix_pyr_instr', 'pyramid_trades', ['instrument_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_pyr_instr', table_name='pyramid_trades')
    op.drop_table('pyramid_trades')
    op.drop_table('risk_checks')
    # ### end Alembic commands ###
