"""notification channels

Revision ID: 950884fdbcc2
Revises: 2adcbe41b214
Create Date: 2026-09-28 01:30:19.621961
"""
from alembic import op
import sqlalchemy as sa


revision = '950884fdbcc2'
down_revision = '2adcbe41b214'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_channels',
    sa.Column('channel', sa.String(), nullable=False),
    sa.Column('target', sa.String(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('min_severity', sa.String(), nullable=False),
    sa.Column('extra', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification_channels'))
    )
    op.create_index(op.f('ix_notification_channels_channel'), 'notification_channels', ['channel'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notification_channels_channel'), table_name='notification_channels')
    op.drop_table('notification_channels')
    # ### end Alembic commands ###
