"""order tickets + exit signals

Revision ID: 99661467dcbc
Revises: 8bd3a06e91c9
Create Date: 2026-09-27 22:03:24.602698
"""
from alembic import op
import sqlalchemy as sa


revision = '99661467dcbc'
down_revision = '8bd3a06e91c9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_tickets',
    sa.Column('decision_id', sa.String(), nullable=False),
    sa.Column('instrument_id', sa.String(), nullable=False),
    sa.Column('portfolio_id', sa.String(), nullable=True),
    sa.Column('side', sa.String(), nullable=False),
    sa.Column('order_type', sa.String(), nullable=False),
    sa.Column('quantity', sa.Double(), nullable=False),
    sa.Column('limit_price', sa.Double(), nullable=True),
    sa.Column('est_notional', sa.Double(), nullable=True),
    sa.Column('est_fees', sa.Double(), nullable=True),
    sa.Column('stop', sa.Double(), nullable=True),
    sa.Column('target1', sa.Double(), nullable=True),
    sa.Column('target2', sa.Double(), nullable=True),
    sa.Column('reward_risk', sa.Double(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('params_hash', sa.String(length=64), nullable=False),
    sa.Column('risk_snapshot', sa.JSON(), nullable=False),
    sa.Column('exposure_before', sa.JSON(), nullable=False),
    sa.Column('exposure_after', sa.JSON(), nullable=False),
    sa.Column('cio_report', sa.JSON(), nullable=False),
    sa.Column('data_freshness', sa.JSON(), nullable=False),
    sa.Column('risk_policy_version', sa.String(length=64), nullable=False),
    sa.Column('approved_by', sa.String(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], name=op.f('fk_order_tickets_approved_by_users')),
    sa.ForeignKeyConstraint(['decision_id'], ['decision_records.id'], name=op.f('fk_order_tickets_decision_id_decision_records')),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], name=op.f('fk_order_tickets_instrument_id_instruments')),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], name=op.f('fk_order_tickets_portfolio_id_portfolios')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_order_tickets'))
    )
    op.create_index(op.f('ix_order_tickets_decision_id'), 'order_tickets', ['decision_id'], unique=False)
    op.create_table('exit_signals',
    sa.Column('instrument_id', sa.String(), nullable=False),
    sa.Column('position_id', sa.String(), nullable=True),
    sa.Column('cls', sa.String(), nullable=False),
    sa.Column('stage', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('order_ticket_id', sa.String(), nullable=True),
    sa.Column('fill_price', sa.Double(), nullable=True),
    sa.Column('filled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], name=op.f('fk_exit_signals_instrument_id_instruments')),
    sa.ForeignKeyConstraint(['order_ticket_id'], ['order_tickets.id'], name=op.f('fk_exit_signals_order_ticket_id_order_tickets')),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], name=op.f('fk_exit_signals_position_id_positions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exit_signals'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exit_signals')
    op.drop_index(op.f('ix_order_tickets_decision_id'), table_name='order_tickets')
    op.drop_table('order_tickets')
    # ### end Alembic commands ###
