"""valuation runs

Revision ID: acf3fda77352
Revises: ce1f3be24427
Create Date: 2026-09-27 20:59:09.849627
"""
from alembic import op
import sqlalchemy as sa


revision = 'acf3fda77352'
down_revision = 'ce1f3be24427'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('valuation_runs',
    sa.Column('group_id', sa.String(), nullable=False),
    sa.Column('instrument_id', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('methodology', sa.String(), nullable=False),
    sa.Column('mandate_version', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('inputs', sa.JSON(), nullable=False),
    sa.Column('outputs', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], name=op.f('fk_valuation_runs_instrument_id_instruments')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_valuation_runs')),
    sa.UniqueConstraint('group_id', 'version', name=op.f('uq_valuation_runs_group_id'))
    )
    op.create_index('ix_val_instr', 'valuation_runs', ['instrument_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_val_instr', table_name='valuation_runs')
    op.drop_table('valuation_runs')
    # ### end Alembic commands ###
