"""model configs + runtime flags

Revision ID: cb4a37b1fcd3
Revises: 9b4db96b36e9
Create Date: 2026-09-28 01:18:56.237709
"""
from alembic import op
import sqlalchemy as sa


revision = 'cb4a37b1fcd3'
down_revision = '9b4db96b36e9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_configs',
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('api_key', sa.String(), nullable=True),
    sa.Column('base_url', sa.String(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_model_configs'))
    )
    op.create_index(op.f('ix_model_configs_provider'), 'model_configs', ['provider'], unique=False)
    op.create_table('runtime_flags',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_runtime_flags')),
    sa.UniqueConstraint('key', name=op.f('uq_runtime_flags_key'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('runtime_flags')
    op.drop_index(op.f('ix_model_configs_provider'), table_name='model_configs')
    op.drop_table('model_configs')
    # ### end Alembic commands ###
