"""dossier + evidence registry

Revision ID: ce1f3be24427
Revises: 15dde5b16638
Create Date: 2026-09-27 20:50:37.235396
"""
from alembic import op
import sqlalchemy as sa


revision = 'ce1f3be24427'
down_revision = '15dde5b16638'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dossiers',
    sa.Column('group_id', sa.String(), nullable=False),
    sa.Column('instrument_id', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('mandate_version', sa.Integer(), nullable=True),
    sa.Column('policy_version', sa.Integer(), nullable=True),
    sa.Column('green_zone_score', sa.Double(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('missing_evidence', sa.JSON(), nullable=False),
    sa.Column('workflow_log', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], name=op.f('fk_dossiers_instrument_id_instruments')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dossiers')),
    sa.UniqueConstraint('group_id', 'version', name=op.f('uq_dossiers_group_id'))
    )
    op.create_index('ix_dossier_instr', 'dossiers', ['instrument_id', 'created_at'], unique=False)
    op.create_table('evidence_items',
    sa.Column('instrument_id', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('concept', sa.String(), nullable=True),
    sa.Column('value', sa.String(), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('period_end', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('source_ref', sa.String(), nullable=True),
    sa.Column('published_at', sa.String(), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], name=op.f('fk_evidence_items_instrument_id_instruments')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evidence_items'))
    )
    op.create_index('ix_evidence_instr', 'evidence_items', ['instrument_id'], unique=False)
    op.create_table('dossier_reviews',
    sa.Column('dossier_id', sa.String(), nullable=False),
    sa.Column('reviewer_id', sa.String(), nullable=True),
    sa.Column('verdict', sa.String(), nullable=False),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dossier_id'], ['dossiers.id'], name=op.f('fk_dossier_reviews_dossier_id_dossiers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dossier_reviews'))
    )
    op.create_index(op.f('ix_dossier_reviews_dossier_id'), 'dossier_reviews', ['dossier_id'], unique=False)
    op.create_table('dossier_sections',
    sa.Column('dossier_id', sa.String(), nullable=False),
    sa.Column('section_no', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dossier_id'], ['dossiers.id'], name=op.f('fk_dossier_sections_dossier_id_dossiers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dossier_sections')),
    sa.UniqueConstraint('dossier_id', 'section_no', name=op.f('uq_dossier_sections_dossier_id'))
    )
    op.create_index(op.f('ix_dossier_sections_dossier_id'), 'dossier_sections', ['dossier_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dossier_sections_dossier_id'), table_name='dossier_sections')
    op.drop_table('dossier_sections')
    op.drop_index(op.f('ix_dossier_reviews_dossier_id'), table_name='dossier_reviews')
    op.drop_table('dossier_reviews')
    op.drop_index('ix_evidence_instr', table_name='evidence_items')
    op.drop_table('evidence_items')
    op.drop_index('ix_dossier_instr', table_name='dossiers')
    op.drop_table('dossiers')
    # ### end Alembic commands ###
