"""mandate versioning + universe eligibility

Revision ID: f6bf1891cf53
Revises: f866152d25bf
Create Date: 2026-09-27 20:19:21.344295
"""
from alembic import op
import sqlalchemy as sa


revision = 'f6bf1891cf53'
down_revision = 'f866152d25bf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('decision_records', sa.Column('mandate_version', sa.Integer(), nullable=True))
    # server_default backfills existing rows; Python-side defaults govern new inserts
    op.add_column('instruments', sa.Column('listing_status', sa.String(), nullable=False, server_default='active'))
    op.add_column('instruments', sa.Column('delisted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('instruments', sa.Column('market_cap', sa.Numeric(precision=24, scale=2), nullable=True))
    op.add_column('instruments', sa.Column('avg_dollar_volume_30d', sa.Numeric(precision=24, scale=2), nullable=True))
    op.create_index(op.f('ix_instruments_listing_status'), 'instruments', ['listing_status'], unique=False)
    op.add_column('mandates', sa.Column('effective_from', sa.DateTime(timezone=True), nullable=True))
    op.add_column('mandates', sa.Column('changed_by', sa.String(), nullable=True))
    op.add_column('mandates', sa.Column('change_note', sa.String(), nullable=True))
    op.add_column('mandates', sa.Column('inv_min_stocks', sa.Integer(), nullable=False, server_default='10'))
    op.add_column('mandates', sa.Column('inv_max_stocks', sa.Integer(), nullable=False, server_default='15'))
    op.add_column('mandates', sa.Column('inv_horizon_years_min', sa.Integer(), nullable=False, server_default='3'))
    op.add_column('mandates', sa.Column('inv_horizon_years_max', sa.Integer(), nullable=False, server_default='5'))
    op.add_column('mandates', sa.Column('trading_max_stocks', sa.Integer(), nullable=False, server_default='5'))
    op.add_column('mandates', sa.Column('trading_horizon', sa.String(), nullable=False, server_default='days_weeks'))
    op.create_foreign_key(op.f('fk_mandates_changed_by_users'), 'mandates', 'users', ['changed_by'], ['id'])
    op.add_column('universe_memberships', sa.Column('reason', sa.String(), nullable=True))
    op.add_column('universes', sa.Column('rules', sa.JSON(), nullable=False, server_default='{}'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('universes', 'rules')
    op.drop_column('universe_memberships', 'reason')
    op.drop_constraint(op.f('fk_mandates_changed_by_users'), 'mandates', type_='foreignkey')
    op.drop_column('mandates', 'trading_horizon')
    op.drop_column('mandates', 'trading_max_stocks')
    op.drop_column('mandates', 'inv_horizon_years_max')
    op.drop_column('mandates', 'inv_horizon_years_min')
    op.drop_column('mandates', 'inv_max_stocks')
    op.drop_column('mandates', 'inv_min_stocks')
    op.drop_column('mandates', 'change_note')
    op.drop_column('mandates', 'changed_by')
    op.drop_column('mandates', 'effective_from')
    op.drop_index(op.f('ix_instruments_listing_status'), table_name='instruments')
    op.drop_column('instruments', 'avg_dollar_volume_30d')
    op.drop_column('instruments', 'market_cap')
    op.drop_column('instruments', 'delisted_at')
    op.drop_column('instruments', 'listing_status')
    op.drop_column('decision_records', 'mandate_version')
    # ### end Alembic commands ###
