"""initial schema

Revision ID: f866152d25bf
Revises: 
Create Date: 2026-09-27 20:00:11.127473
"""
from alembic import op
import sqlalchemy as sa


revision = 'f866152d25bf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_defs',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('layer', sa.String(), nullable=False),
    sa.Column('primary_question', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_defs')),
    sa.UniqueConstraint('key', name=op.f('uq_agent_defs_key'))
    )
    op.create_table('data_providers',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('capabilities', sa.JSON(), nullable=False),
    sa.Column('rate_limit', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_data_providers')),
    sa.UniqueConstraint('key', name=op.f('uq_data_providers_key'))
    )
    op.create_table('exchanges',
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exchanges')),
    sa.UniqueConstraint('code', name=op.f('uq_exchanges_code'))
    )
    op.create_table('macro_series',
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('frequency', sa.String(), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_macro_series')),
    sa.UniqueConstraint('source', 'code', name=op.f('uq_macro_series_source'))
    )
    op.create_table('mandates',
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('investment_split_pct', sa.Double(), nullable=False),
    sa.Column('trading_split_pct', sa.Double(), nullable=False),
    sa.Column('target_return_min', sa.Double(), nullable=False),
    sa.Column('target_return_max', sa.Double(), nullable=False),
    sa.Column('max_drawdown_pct', sa.Double(), nullable=False),
    sa.Column('min_sharpe', sa.Double(), nullable=False),
    sa.Column('min_win_rate_pct', sa.Double(), nullable=False),
    sa.Column('min_risk_reward', sa.Double(), nullable=False),
    sa.Column('green_zone_pass_score', sa.Integer(), nullable=False),
    sa.Column('margin_of_safety_min_pct', sa.Double(), nullable=False),
    sa.Column('extra', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mandates')),
    sa.UniqueConstraint('tenant_id', 'version', name=op.f('uq_mandates_tenant_id'))
    )
    op.create_index(op.f('ix_mandates_tenant_id'), 'mandates', ['tenant_id'], unique=False)
    op.create_table('portfolios',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('base_currency', sa.String(length=3), nullable=False),
    sa.Column('broker', sa.String(), nullable=True),
    sa.Column('external_ref', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_portfolios')),
    sa.UniqueConstraint('tenant_id', 'name', name=op.f('uq_portfolios_tenant_id'))
    )
    op.create_index(op.f('ix_portfolios_tenant_id'), 'portfolios', ['tenant_id'], unique=False)
    op.create_table('roles',
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('permissions', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles')),
    sa.UniqueConstraint('tenant_id', 'name', name=op.f('uq_roles_tenant_id'))
    )
    op.create_table('sectors',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sectors')),
    sa.UniqueConstraint('name', name=op.f('uq_sectors_name'))
    )
    op.create_table('universes',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('tier', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_universes')),
    sa.UniqueConstraint('tenant_id', 'name', name=op.f('uq_universes_tenant_id'))
    )
    op.create_index(op.f('ix_universes_tenant_id'), 'universes', ['tenant_id'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('tenant_id', 'email', name=op.f('uq_users_tenant_id'))
    )
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.create_table('alerts',
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('context', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('acked_by', sa.String(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['acked_by'], ['users.id'], name=op.f('fk_alerts_acked_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alerts'))
    )
    op.create_index(op.f('ix_alerts_status'), 'alerts', ['status'], unique=False)
    op.create_index(op.f('ix_alerts_tenant_id'), 'alerts', ['tenant_id'], unique=False)
    op.create_table('audit_events',
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('actor_id', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_audit_events_actor_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_events'))
    )
    op.create_index('ix_audit_entity', 'audit_events', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_audit_events_action'), 'audit_events', ['action'], unique=False)
    op.create_index(op.f('ix_audit_events_at'), 'audit_events', ['at'], unique=False)
    op.create_index(op.f('ix_audit_events_tenant_id'), 'audit_events', ['tenant_id'], unique=False)
    op.create_table('economic_releases',
    sa.Column('series_id', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('release_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period', sa.Date(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['series_id'], ['macro_series.id'], name=op.f('fk_economic_releases_series_id_macro_series'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_economic_releases')),
    sa.UniqueConstraint('series_id', 'release_at', name=op.f('uq_economic_releases_series_id'))
    )
    op.create_index(op.f('ix_economic_releases_release_at'), 'economic_releases', ['release_at'], unique=False)
    op.create_table('industries',
    sa.Column('sector_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['sector_id'], ['sectors.id'], name=op.f('fk_industries_sector_id_sectors')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_industries')),
    sa.UniqueConstraint('sector_id', 'name', name=op.f('uq_industries_sector_id'))
    )
    op.create_table('jobs',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('schedule', sa.String(), nullable=True),
    sa.Column('provider_id', sa.String(), nullable=True),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['data_providers.id'], name=op.f('fk_jobs_provider_id_data_providers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_jobs')),
    sa.UniqueConstraint('key', name=op.f('uq_jobs_key'))
    )
    op.create_table('macro_observations',
    sa.Column('series_id', sa.String(), nullable=False),
    sa.Column('value', sa.Numeric(precision=24, scale=6), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('source_ref', sa.String(), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('quality', sa.String(), nullable=False),
    sa.Column('supersedes_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['series_id'], ['macro_series.id'], name=op.f('fk_macro_observations_series_id_macro_series'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_macro_observations')),
    sa.UniqueConstraint('series_id', 'observed_at', 'published_at', name=op.f('uq_macro_observations_series_id'))
    )
    op.create_index(op.f('ix_macro_observations_published_at'), 'macro_observations', ['published_at'], unique=False)
    op.create_index(op.f('ix_macro_observations_series_id'), 'macro_observations', ['series_id'], unique=False)
    op.create_index(op.f('ix_macro_observations_source'), 'macro_observations', ['source'], unique=False)
    op.create_table('provider_credential_meta',
    sa.Column('provider_id', sa.String(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('secret_ref', sa.String(), nullable=False),
    sa.Column('rotated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['data_providers.id'], name=op.f('fk_provider_credential_meta_provider_id_data_providers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_provider_credential_meta')),
    sa.UniqueConstraint('provider_id', 'key', name=op.f('uq_provider_credential_meta_provider_id'))
    )
    op.create_index(op.f('ix_provider_credential_meta_provider_id'), 'provider_credential_meta', ['provider_id'], unique=False)
    op.create_table('sessions',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ip', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sessions'))
    )
    op.create_index(op.f('ix_sessions_token_hash'), 'sessions', ['token_hash'], unique=True)
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_table('sync_status',
    sa.Column('provider_id', sa.String(), nullable=False),
    sa.Column('dataset', sa.String(), nullable=False),
    sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.String(), nullable=True),
    sa.Column('lag_seconds', sa.Integer(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['data_providers.id'], name=op.f('fk_sync_status_provider_id_data_providers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sync_status')),
    sa.UniqueConstraint('provider_id', 'dataset', name=op.f('uq_sync_status_provider_id'))
    )
    op.create_index(op.f('ix_sync_status_provider_id'), 'sync_status', ['provider_id'], unique=False)
    op.create_table('user_roles',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('role_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_user_roles_role_id_roles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_roles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id', name=op.f('pk_user_roles'))
    )
    op.create_table('watchlists',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_watchlists_owner_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_watchlists')),
    sa.UniqueConstraint('tenant_id', 'name', name=op.f('uq_watchlists_tenant_id'))
    )
    op.create_index(op.f('ix_watchlists_tenant_id'), 'watchlists', ['tenant_id'], unique=False)
    op.create_table('instruments',
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('asset_class', sa.String(), nullable=False),
    sa.Column('exchange_id', sa.String(), nullable=True),
    sa.Column('sector_id', sa.String(), nullable=True),
    sa.Column('industry_id', sa.String(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['exchange_id'], ['exchanges.id'], name=op.f('fk_instruments_exchange_id_exchanges')),
    sa.ForeignKeyConstraint(['industry_id'], ['industries.id'], name=op.f('fk_instruments_industry_id_industries')),
    sa.ForeignKeyConstraint(['sector_id'], ['sectors.id'], name=op.f('fk_instruments_sector_id_sectors')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_instruments')),
    sa.UniqueConstraint('exchange_id', 'symbol', name=op.f('uq_instruments_exchange_id'))
    )
    op.create_index(op.f('ix_instruments_asset_class'), 'instruments', ['asset_class'], unique=False)
    op.create_index(op.f('ix_instruments_symbol'), 'instruments', ['symbol'], unique=False)
    op.create_table('job_runs',
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('records_in', sa.Integer(), nullable=False),
    sa.Column('records_ok', sa.Integer(), nullable=False),
    sa.Column('records_quarantined', sa.Integer(), nullable=False),
    sa.Column('error', sa.String(), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_job_runs_job_id_jobs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_runs'))
    )
    op.create_index(op.f('ix_job_runs_job_id'), 'job_runs', ['job_id'], unique=False)
    op.create_index(op.f('ix_job_runs_status'), 'job_runs', ['status'], unique=False)
    op.create_table('agent_runs',
    sa.Column('agent_key', sa.String(), nullable=False),
    sa.Column('instrument_id', sa.String(), nullable=True),
    sa.Column('decision_run_id', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('prompt_hash', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('inputs', sa.JSON(), nullable=False),
    sa.Column('error', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], name=op.f('fk_agent_runs_instrument_id_instruments')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_runs'))
    )
    op.create_index(op.f('ix_agent_runs_agent_key'), 'agent_runs', ['agent_key'], unique=False)
    op.create_index(op.f('ix_agent_runs_decision_run_id'), 'agent_runs', ['decision_run_id'], unique=False)
    op.create_index(op.f('ix_agent_runs_instrument_id'), 'agent_runs', ['instrument_id'], unique=False)
    op.create_index(op.f('ix_agent_runs_tenant_id'), 'agent_runs', ['tenant_id'], unique=False)
    op.create_table('analysis_runs',
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('instrument_id', sa.String(), nullable=True),
    sa.Column('engine_version', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('inputs', sa.JSON(), nullable=False),
    sa.Column('outputs', sa.JSON(), nullable=False),
    sa.Column('error', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], name=op.f('fk_analysis_runs_instrument_id_instruments')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_analysis_runs'))
    )
    op.create_index('ix_analysis_kind_instrument', 'analysis_runs', ['kind', 'instrument_id'], unique=False)
    op.create_index(op.f('ix_analysis_runs_instrument_id'), 'analysis_runs', ['instrument_id'], unique=False)
    op.create_index(op.f('ix_analysis_runs_tenant_id'), 'analysis_runs', ['tenant_id'], unique=False)
    op.create_table('corporate_actions',
    sa.Column('instrument_id', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('ex_date', sa.Date(), nullable=False),
    sa.Column('ratio', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], name=op.f('fk_corporate_actions_instrument_id_instruments'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_corporate_actions')),
    sa.UniqueConstraint('instrument_id', 'kind', 'ex_date', 'ratio', name=op.f('uq_corporate_actions_instrument_id'))
    )
    op.create_index(op.f('ix_corporate_actions_instrument_id'), 'corporate_actions', ['instrument_id'], unique=False)
    op.create_table('decision_records',
    sa.Column('instrument_id', sa.String(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('stage', sa.String(), nullable=False),
    sa.Column('verdict', sa.String(), nullable=True),
    sa.Column('gate_results', sa.JSON(), nullable=False),
    sa.Column('agent_scores', sa.JSON(), nullable=False),
    sa.Column('numbers', sa.JSON(), nullable=False),
    sa.Column('cio_confidence', sa.Double(), nullable=True),
    sa.Column('supersedes_id', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], name=op.f('fk_decision_records_instrument_id_instruments')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_decision_records'))
    )
    op.create_index('ix_decision_instr', 'decision_records', ['instrument_id', 'at'], unique=False)
    op.create_index(op.f('ix_decision_records_at'), 'decision_records', ['at'], unique=False)
    op.create_index(op.f('ix_decision_records_tenant_id'), 'decision_records', ['tenant_id'], unique=False)
    op.create_table('financial_statements',
    sa.Column('instrument_id', sa.String(), nullable=False),
    sa.Column('statement', sa.String(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('period', sa.String(), nullable=False),
    sa.Column('form', sa.String(), nullable=True),
    sa.Column('filed_at', sa.Date(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('source_ref', sa.String(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], name=op.f('fk_financial_statements_instrument_id_instruments'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_financial_statements')),
    sa.UniqueConstraint('instrument_id', 'statement', 'period_end', 'source', 'form', name=op.f('uq_financial_statements_instrument_id'))
    )
    op.create_index(op.f('ix_financial_statements_instrument_id'), 'financial_statements', ['instrument_id'], unique=False)
    op.create_index(op.f('ix_financial_statements_period_end'), 'financial_statements', ['period_end'], unique=False)
    op.create_table('fundamental_observations',
    sa.Column('instrument_id', sa.String(), nullable=False),
    sa.Column('concept', sa.String(), nullable=False),
    sa.Column('value', sa.Numeric(precision=28, scale=6), nullable=False),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('fiscal_period', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('source_ref', sa.String(), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('quality', sa.String(), nullable=False),
    sa.Column('supersedes_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], name=op.f('fk_fundamental_observations_instrument_id_instruments'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fundamental_observations')),
    sa.UniqueConstraint('instrument_id', 'concept', 'period_end', 'source', 'published_at', name=op.f('uq_fundamental_observations_instrument_id'))
    )
    op.create_index(op.f('ix_fundamental_observations_concept'), 'fundamental_observations', ['concept'], unique=False)
    op.create_index(op.f('ix_fundamental_observations_instrument_id'), 'fundamental_observations', ['instrument_id'], unique=False)
    op.create_index(op.f('ix_fundamental_observations_period_end'), 'fundamental_observations', ['period_end'], unique=False)
    op.create_index(op.f('ix_fundamental_observations_published_at'), 'fundamental_observations', ['published_at'], unique=False)
    op.create_index(op.f('ix_fundamental_observations_source'), 'fundamental_observations', ['source'], unique=False)
    op.create_table('instrument_identifiers',
    sa.Column('instrument_id', sa.String(), nullable=False),
    sa.Column('scheme', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], name=op.f('fk_instrument_identifiers_instrument_id_instruments'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_instrument_identifiers')),
    sa.UniqueConstraint('scheme', 'value', name=op.f('uq_instrument_identifiers_scheme'))
    )
    op.create_index(op.f('ix_instrument_identifiers_instrument_id'), 'instrument_identifiers', ['instrument_id'], unique=False)
    op.create_table('ohlcv_bars',
    sa.Column('instrument_id', sa.String(), nullable=False),
    sa.Column('timeframe', sa.String(), nullable=False),
    sa.Column('time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('open', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('high', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('low', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('close', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('volume', sa.Numeric(precision=28, scale=2), nullable=True),
    sa.Column('adjusted', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], name=op.f('fk_ohlcv_bars_instrument_id_instruments'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ohlcv_bars')),
    sa.UniqueConstraint('instrument_id', 'timeframe', 'time', 'source', 'adjusted', name=op.f('uq_ohlcv_bars_instrument_id'))
    )
    op.create_index(op.f('ix_ohlcv_bars_instrument_id'), 'ohlcv_bars', ['instrument_id'], unique=False)
    op.create_index(op.f('ix_ohlcv_bars_time'), 'ohlcv_bars', ['time'], unique=False)
    op.create_table('positions',
    sa.Column('portfolio_id', sa.String(), nullable=False),
    sa.Column('instrument_id', sa.String(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=28, scale=8), nullable=False),
    sa.Column('avg_cost', sa.Numeric(precision=28, scale=8), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('thesis_ref', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], name=op.f('fk_positions_instrument_id_instruments')),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], name=op.f('fk_positions_portfolio_id_portfolios'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_positions')),
    sa.UniqueConstraint('portfolio_id', 'instrument_id', name=op.f('uq_positions_portfolio_id'))
    )
    op.create_index(op.f('ix_positions_portfolio_id'), 'positions', ['portfolio_id'], unique=False)
    op.create_table('quarantined_records',
    sa.Column('job_run_id', sa.String(), nullable=True),
    sa.Column('provider_id', sa.String(), nullable=True),
    sa.Column('target_table', sa.String(), nullable=False),
    sa.Column('raw', sa.JSON(), nullable=False),
    sa.Column('errors', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_run_id'], ['job_runs.id'], name=op.f('fk_quarantined_records_job_run_id_job_runs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['provider_id'], ['data_providers.id'], name=op.f('fk_quarantined_records_provider_id_data_providers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quarantined_records'))
    )
    op.create_table('risk_assessments',
    sa.Column('instrument_id', sa.String(), nullable=True),
    sa.Column('portfolio_id', sa.String(), nullable=True),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('dimensions', sa.JSON(), nullable=False),
    sa.Column('limit_breaches', sa.JSON(), nullable=False),
    sa.Column('verdict', sa.String(), nullable=False),
    sa.Column('engine_version', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], name=op.f('fk_risk_assessments_instrument_id_instruments')),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], name=op.f('fk_risk_assessments_portfolio_id_portfolios')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_risk_assessments'))
    )
    op.create_index(op.f('ix_risk_assessments_instrument_id'), 'risk_assessments', ['instrument_id'], unique=False)
    op.create_index(op.f('ix_risk_assessments_portfolio_id'), 'risk_assessments', ['portfolio_id'], unique=False)
    op.create_table('universe_memberships',
    sa.Column('universe_id', sa.String(), nullable=False),
    sa.Column('instrument_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], name=op.f('fk_universe_memberships_instrument_id_instruments'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['universe_id'], ['universes.id'], name=op.f('fk_universe_memberships_universe_id_universes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_universe_memberships')),
    sa.UniqueConstraint('universe_id', 'instrument_id', name=op.f('uq_universe_memberships_universe_id'))
    )
    op.create_index(op.f('ix_universe_memberships_instrument_id'), 'universe_memberships', ['instrument_id'], unique=False)
    op.create_index(op.f('ix_universe_memberships_universe_id'), 'universe_memberships', ['universe_id'], unique=False)
    op.create_table('watchlist_items',
    sa.Column('watchlist_id', sa.String(), nullable=False),
    sa.Column('instrument_id', sa.String(), nullable=False),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('reason_code', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], name=op.f('fk_watchlist_items_instrument_id_instruments'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['watchlist_id'], ['watchlists.id'], name=op.f('fk_watchlist_items_watchlist_id_watchlists'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_watchlist_items')),
    sa.UniqueConstraint('watchlist_id', 'instrument_id', name=op.f('uq_watchlist_items_watchlist_id'))
    )
    op.create_index(op.f('ix_watchlist_items_watchlist_id'), 'watchlist_items', ['watchlist_id'], unique=False)
    op.create_table('agent_outputs',
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('recommendation', sa.String(), nullable=True),
    sa.Column('score', sa.Double(), nullable=True),
    sa.Column('confidence', sa.Double(), nullable=True),
    sa.Column('data_quality', sa.String(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['agent_runs.id'], name=op.f('fk_agent_outputs_run_id_agent_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_outputs'))
    )
    op.create_index(op.f('ix_agent_outputs_run_id'), 'agent_outputs', ['run_id'], unique=False)
    op.create_table('approvals',
    sa.Column('decision_id', sa.String(), nullable=True),
    sa.Column('requested_by', sa.String(), nullable=True),
    sa.Column('approved_by', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], name=op.f('fk_approvals_approved_by_users')),
    sa.ForeignKeyConstraint(['decision_id'], ['decision_records.id'], name=op.f('fk_approvals_decision_id_decision_records')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_approvals'))
    )
    op.create_index(op.f('ix_approvals_decision_id'), 'approvals', ['decision_id'], unique=False)
    op.create_index('ix_approvals_status', 'approvals', ['status'], unique=False)
    op.create_table('trades',
    sa.Column('portfolio_id', sa.String(), nullable=False),
    sa.Column('instrument_id', sa.String(), nullable=False),
    sa.Column('side', sa.String(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=28, scale=8), nullable=False),
    sa.Column('price', sa.Numeric(precision=28, scale=8), nullable=False),
    sa.Column('fees', sa.Numeric(precision=28, scale=8), nullable=False),
    sa.Column('traded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('decision_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['decision_id'], ['decision_records.id'], name=op.f('fk_trades_decision_id_decision_records')),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], name=op.f('fk_trades_instrument_id_instruments')),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], name=op.f('fk_trades_portfolio_id_portfolios'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trades'))
    )
    op.create_index(op.f('ix_trades_portfolio_id'), 'trades', ['portfolio_id'], unique=False)
    op.create_table('evidence_refs',
    sa.Column('agent_output_id', sa.String(), nullable=False),
    sa.Column('ref_table', sa.String(), nullable=False),
    sa.Column('ref_id', sa.String(), nullable=False),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_output_id'], ['agent_outputs.id'], name=op.f('fk_evidence_refs_agent_output_id_agent_outputs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evidence_refs')),
    sa.UniqueConstraint('agent_output_id', 'ref_table', 'ref_id', name=op.f('uq_evidence_refs_agent_output_id'))
    )
    op.create_index(op.f('ix_evidence_refs_agent_output_id'), 'evidence_refs', ['agent_output_id'], unique=False)
    op.create_table('ledger_entries',
    sa.Column('portfolio_id', sa.String(), nullable=False),
    sa.Column('trade_id', sa.String(), nullable=True),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=28, scale=8), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('memo', sa.String(), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], name=op.f('fk_ledger_entries_portfolio_id_portfolios'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.id'], name=op.f('fk_ledger_entries_trade_id_trades')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ledger_entries'))
    )
    op.create_index(op.f('ix_ledger_entries_at'), 'ledger_entries', ['at'], unique=False)
    op.create_index(op.f('ix_ledger_entries_portfolio_id'), 'ledger_entries', ['portfolio_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ledger_entries_portfolio_id'), table_name='ledger_entries')
    op.drop_index(op.f('ix_ledger_entries_at'), table_name='ledger_entries')
    op.drop_table('ledger_entries')
    op.drop_index(op.f('ix_evidence_refs_agent_output_id'), table_name='evidence_refs')
    op.drop_table('evidence_refs')
    op.drop_index(op.f('ix_trades_portfolio_id'), table_name='trades')
    op.drop_table('trades')
    op.drop_index('ix_approvals_status', table_name='approvals')
    op.drop_index(op.f('ix_approvals_decision_id'), table_name='approvals')
    op.drop_table('approvals')
    op.drop_index(op.f('ix_agent_outputs_run_id'), table_name='agent_outputs')
    op.drop_table('agent_outputs')
    op.drop_index(op.f('ix_watchlist_items_watchlist_id'), table_name='watchlist_items')
    op.drop_table('watchlist_items')
    op.drop_index(op.f('ix_universe_memberships_universe_id'), table_name='universe_memberships')
    op.drop_index(op.f('ix_universe_memberships_instrument_id'), table_name='universe_memberships')
    op.drop_table('universe_memberships')
    op.drop_index(op.f('ix_risk_assessments_portfolio_id'), table_name='risk_assessments')
    op.drop_index(op.f('ix_risk_assessments_instrument_id'), table_name='risk_assessments')
    op.drop_table('risk_assessments')
    op.drop_table('quarantined_records')
    op.drop_index(op.f('ix_positions_portfolio_id'), table_name='positions')
    op.drop_table('positions')
    op.drop_index(op.f('ix_ohlcv_bars_time'), table_name='ohlcv_bars')
    op.drop_index(op.f('ix_ohlcv_bars_instrument_id'), table_name='ohlcv_bars')
    op.drop_table('ohlcv_bars')
    op.drop_index(op.f('ix_instrument_identifiers_instrument_id'), table_name='instrument_identifiers')
    op.drop_table('instrument_identifiers')
    op.drop_index(op.f('ix_fundamental_observations_source'), table_name='fundamental_observations')
    op.drop_index(op.f('ix_fundamental_observations_published_at'), table_name='fundamental_observations')
    op.drop_index(op.f('ix_fundamental_observations_period_end'), table_name='fundamental_observations')
    op.drop_index(op.f('ix_fundamental_observations_instrument_id'), table_name='fundamental_observations')
    op.drop_index(op.f('ix_fundamental_observations_concept'), table_name='fundamental_observations')
    op.drop_table('fundamental_observations')
    op.drop_index(op.f('ix_financial_statements_period_end'), table_name='financial_statements')
    op.drop_index(op.f('ix_financial_statements_instrument_id'), table_name='financial_statements')
    op.drop_table('financial_statements')
    op.drop_index(op.f('ix_decision_records_tenant_id'), table_name='decision_records')
    op.drop_index(op.f('ix_decision_records_at'), table_name='decision_records')
    op.drop_index('ix_decision_instr', table_name='decision_records')
    op.drop_table('decision_records')
    op.drop_index(op.f('ix_corporate_actions_instrument_id'), table_name='corporate_actions')
    op.drop_table('corporate_actions')
    op.drop_index(op.f('ix_analysis_runs_tenant_id'), table_name='analysis_runs')
    op.drop_index(op.f('ix_analysis_runs_instrument_id'), table_name='analysis_runs')
    op.drop_index('ix_analysis_kind_instrument', table_name='analysis_runs')
    op.drop_table('analysis_runs')
    op.drop_index(op.f('ix_agent_runs_tenant_id'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_instrument_id'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_decision_run_id'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_agent_key'), table_name='agent_runs')
    op.drop_table('agent_runs')
    op.drop_index(op.f('ix_job_runs_status'), table_name='job_runs')
    op.drop_index(op.f('ix_job_runs_job_id'), table_name='job_runs')
    op.drop_table('job_runs')
    op.drop_index(op.f('ix_instruments_symbol'), table_name='instruments')
    op.drop_index(op.f('ix_instruments_asset_class'), table_name='instruments')
    op.drop_table('instruments')
    op.drop_index(op.f('ix_watchlists_tenant_id'), table_name='watchlists')
    op.drop_table('watchlists')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_sync_status_provider_id'), table_name='sync_status')
    op.drop_table('sync_status')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_token_hash'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_provider_credential_meta_provider_id'), table_name='provider_credential_meta')
    op.drop_table('provider_credential_meta')
    op.drop_index(op.f('ix_macro_observations_source'), table_name='macro_observations')
    op.drop_index(op.f('ix_macro_observations_series_id'), table_name='macro_observations')
    op.drop_index(op.f('ix_macro_observations_published_at'), table_name='macro_observations')
    op.drop_table('macro_observations')
    op.drop_table('jobs')
    op.drop_table('industries')
    op.drop_index(op.f('ix_economic_releases_release_at'), table_name='economic_releases')
    op.drop_table('economic_releases')
    op.drop_index(op.f('ix_audit_events_tenant_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_at'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_action'), table_name='audit_events')
    op.drop_index('ix_audit_entity', table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_alerts_tenant_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_status'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_universes_tenant_id'), table_name='universes')
    op.drop_table('universes')
    op.drop_table('sectors')
    op.drop_table('roles')
    op.drop_index(op.f('ix_portfolios_tenant_id'), table_name='portfolios')
    op.drop_table('portfolios')
    op.drop_index(op.f('ix_mandates_tenant_id'), table_name='mandates')
    op.drop_table('mandates')
    op.drop_table('macro_series')
    op.drop_table('exchanges')
    op.drop_table('data_providers')
    op.drop_table('agent_defs')
    # ### end Alembic commands ###
